### ISSUE TITLE
Style feature request: change Step headings to simple numbered list or paragraphs

### ISSUE THREAD

**Issue by RichSteele** [deathau/cooklang-obsidian#4]
Instead of the Step 1, Step 2, etc. headings I would prefer a simple numbered list. Actually, I prefer no numbers, just paragraphs. Can an option be added to control the step style?

**Comment by deathau** [comment]
You can style (or hide) it yourself using a CSS snippet for now, but I'll keep this open and consider adding some more default options for style.
To achieve what you want with no headings or numbers, just paragraphs, use this CSS Snippet:
```css
body .workspace-leaf-content[data-type=cook] ol.method > li::before { content: ""; }
```
(just save it in a css file — for example, `cooklang-no-step-headings.css` — in your snippets folder: `<your vault>/.obisidian/snippets` and turn it on in Obsidian's appearance settings.
